baseURL = "http://huidengvan.netlify.com"
title = "Huideng Group Vancouver"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-177233706-1"

Paginate = 50
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.info]
description = "慧灯小组温哥华"
title404 = "Nothing's here!"

[params.assets]
favicon = "huideng.ico"
#customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Huidengvan (huidengvan@gmail.com)"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "huidengvan"
email = "huidengvan@gmail.com"
facebook = "huidengvan"
#github = "huidengvan"
#gitlab = "huidengvan"
instagram = "huidengvan"
#linkedin = "huidengvan"
twitter = "huidengvan"
telegram = "huidengvan"
#google_scholar = "qc6CJjYAAAAJ"
youtube = "UCp-m_8n7201qjJv4p9fScHg"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "huidengvan"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "huidengvan"
repository = "minimo"

#[params.search]
#client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    languageDirection = 'ltr'
    weight = 1

[menu]

[[menu.main]]
  identifier = "hdzhg"
  name = "慧灯之光"
  title = "慧灯之光"
  url = "http://www.huidengzhiguang.com"
  weight = 1.0

  [[menu.main]]
  identifier = "posts"
  name = "共修通知"
  title = "共修通知"
  url = "/posts/"
  weight = 3.0

  [[menu.main]]
  identifier = "archive"
  name = "共修存档"
  title = "共修存档"
  url = "/archive/"
  weight = 9.0

[[menu.main]]
  identifier = "zoom1"
  name = "Zoom1"
  title = "进入Zoom共修房间1"
  url = "https://us02web.zoom.us/j/7789995278?pwd=VjZmbWJFY2k2K0E5RVB2cTNIQmhqUT09"
  weight = 3.1

[[menu.main]]
  identifier = "zoom2"
  name = "Zoom2"
  title = "进入Zoom共修房间2"
  url = "https://us02web.zoom.us/j/7672270786?pwd=bjRzNVpOT0g1cWF3WWVqVE1PZzlWZz09"
  weight = 3.2
  
 [[menu.main]]
  identifier = "zoom3"
  name = "Zoom3"
  title = "进入Zoom共修房间3"
  url = "https://us06web.zoom.us/j/2200939348?pwd=zCHP3llIc31B0o587BY6mkJUaLIvag.1"
  weight = 3.3

 [[menu.main]]
  identifier = "mm"
  name = "聊天室"
  title = "进入MatterMost聊天室"
  url = "https://mm.hdcxb.net"
  weight = 4.0

[[menu.main]]
  identifier = "cxb"
  name = "学修参考"
  title = "学修参考"
  url = "https://huidengchanxiu.net/"
  weight = 4.0
  
 [[menu.main]]
  identifier = "fhfy"
  name = "佛慧法语"
  title = "佛慧法语"
  url = "https://www.fohuifayu.com/"
  weight = 5.0

 [[menu.main]]
  identifier = "box"
  name = "禅修班·网盘"
  title = "网盘"
  url = "https://box.hdcxb.net/"
  weight = 5.1
  
  [[menu.main]]
  identifier = "zangli"
  name = "藏历"
  title = "藏历"
  url = "https://zangli.pro/"
  weight = 5.2

  
