name: deploy-hugo-huidengvan-com

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      # Install and build Docusaurus website
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Upload ftp
        if: success()
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTPHOST }}
          user: ${{ secrets.FTPUSER }}
          password: ${{ secrets.FTPPASS }}
          localDir: "public"
          remoteDir: "/"
          # options: "--delete --asci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

