name: Push to GitHub Pages on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: huidengvan/huidengvan.github.io
          destination_token: ${{ secrets.TOKEN }}
